title: Lucino Garcia # your name (or website title) here
logo: "/images/headshot.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/lucino-garcia/">My LinkedIn Profile</a> <br>
  <a href="https://github.com/LucinoGarcia">My GitHub Profile</a> <br>
  LGarciaJr@fastmail.com 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
